config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/display', to: 'home#display'
  get '/save', to: 'home#save'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cryptocurrency.rb
class Cryptocurrency < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @cryptocurrencies = Cryptocurrency.all
  end

  def save
    StartScrap.new.perform
    @cryptocurrencies = Cryptocurrency.all
    redirect_to root_path
  end

  def display
    @cryptocurrencies = Cryptocurrency.all

    unless params[:cryptocurrency_id].nil?
      @currency = Cryptocurrency.find(params[:cryptocurrency_id])
    end

    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Cryptocurrency Tracker</h1>

<p>Click the button bellow to retrieve all updated cryptocurrencies and their values:</p>
<%= link_to '<button type="button">Scrap!</button>'.html_safe, save_path %>

<% unless Cryptocurrency.all.empty? %>
  <p>Select you favorite currency to know its value!</p>

  <%= form_tag url_for(action: 'display'), method: 'get' do %>
    Cryptocurrency name:
    <%= select_tag :cryptocurrency_id, options_for_select(
      @cryptocurrencies.map { |cryptocurrency| [cryptocurrency.name, cryptocurrency.id] }
    ) %>

  <%= submit_tag 'Go' %>

  <% end %>

  <% unless @currency.nil? %>
    <p>The price of <%= @currency.name %> is <%= @currency.value %></p>
  <% end %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>